version: '3.9'

services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD
      MYSQL_DATABASE: DBNAME
      MYSQL_USER: USERNAME
      MYSQL_PASSWORD: PASSWORD
    ports:
      - "3306:3306"
      - "33060:33060"

  app:
    build:
      context: app
    depends_on:
      - mysql
    ports:
      - "5000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "81:80"
